#! /bin/sh

sxhkd &
VBoxClient-all &
polybar -r pbar &
alacritty &

bspc monitor -d desktop code firefox

bspc config border_width         2
bspc config window_gap           8

bspc config bottom_padding  10
bspc config bottom_padding  20
bspc config left_padding    20
bspc config right_padding   20
bspc config active_border_color  \#41287D
bspc config normal_border_color  \#F56262

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# feh --bg-center ~/Pictures/bear-deer-sunset-wallpaper.jpg
feh --bg-center --randomize ~/Pictures/wallpaper/*
